QuikOpenConfig={};

QuikOpenConfig.TypeConf={
    ["3-9-1"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-2"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-3"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-4"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-5"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-6"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-7"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
    ["3-9-8"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="2", GuideCoef3="2"},
	["3-35-0"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="4", GuideCoef3="1"},
	-- ["3-7-27"] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1",  GuideCoef3="1"},
    -- ["3-7-28"] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	-- ["3-13-15"] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="2", GuideCoef3="1"},
	-- ["3-7-26"] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="2"},

	["3-31-0"] = {GuideType=1, GuideCoef1="SpiritualEquipUI", GuideCoef2="3", GuideCoef3="2"},
	["3-32-0"] = {GuideType=1, GuideCoef1="SpiritualEquipUI", GuideCoef2="4", GuideCoef3="1"},
	["3-33-0"] = {GuideType=1, GuideCoef1="SpiritualEquipUI", GuideCoef2="2", GuideCoef3="2"},
	["3-34-0"] = {GuideType=1, GuideCoef1="SpiritualEquipUI", GuideCoef2="3", GuideCoef3="1"},

	--器灵
	["3-7-29"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="5", GuideCoef3="3"},
	["3-7-30"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="5", GuideCoef3="2"},
	["3-7-31"] = {GuideType=1, GuideCoef1="EquipUI", GuideCoef2="5", GuideCoef3="1"},
	-- ["7-1-0"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
    -- ["7-6-0"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
    -- ["7-2-1"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-2"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-3"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-4"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-5"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-6"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-7"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-8"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-9"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-10"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-11"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
    -- ["7-2-12"] = {GuideType=6, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},

}

QuikOpenConfig.KeyNameConf = {
    ['祈福卷轴1']   = {GuideType=6, GuideCoef1="PrayUI"},
    ['祈福卷轴2']   = {GuideType=6, GuideCoef1="PrayUI"},
    ['祈福卷轴3']   = {GuideType=6, GuideCoef1="PrayUI"},
    ['骰子1'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20978"},
    ['骰子2'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20979"},
    ['骰子3'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20980"},
    ['骰子4'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20981"},
    ['骰子5'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20982"},
    ['骰子6'] = {GuideType=1, GuideCoef1="MonopolyUI", GuideCoef2="1", GuideCoef3="20983"},
	["更名卡"] ={GuideType=6, GuideCoef1="RoleRenameUI"},
	["帮派更名卡"] ={GuideType=8, GuideCoef1="FactionUI"},

  }
 --宠物道具 
  QuikOpenConfig.KeyNameConf2 = {
	['宠物装备洗炼石'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物装备洗炼锁'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="2", GuideCoef3="1"},
	['混元石'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="2"},
	['宠物装备强化石'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	['宠物装备强化石2'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	['宠物装备强化石3'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	['宠物装备强化石4'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	['宠物装备强化石5'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
	['宠物强化保固石'] = {GuideType=11, GuideCoef1="PetEquipRepairUI", GuideCoef2="1", GuideCoef3="1"},
    ['还原丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="3"},
	['高级还原丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="3"},
	['超级还原丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="3"},
	['普通洗练符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
	['高级洗练符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
	['洗练锁定符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="3", GuideCoef3="1"},
	['合成幸运符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="4", GuideCoef3="1"},
	['合成大幸运符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="4", GuideCoef3="1"},
	['合成超幸运符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="4", GuideCoef3="1"},	
	['宠物经验丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物经验丹2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物经验丹3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物大经验丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['忠诚度1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['忠诚度2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['忠诚度3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['忠诚度4'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['寿命丹1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['寿命丹2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['寿命丹3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物复活药'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['重洗髓丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点4'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点5'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点6'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点7'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点8'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点9'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点10'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点11'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点12'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点13'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点14'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点15'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点16'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点17'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点18'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点19'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['宠物洗点20'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级物攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级物攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级物攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物攻仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物攻神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级法攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级法攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级法攻丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法攻仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法攻神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级物防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级物防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级物防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物防仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物防神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级法防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级法防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级法防丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法防仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法防神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级血量上限丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级血量上限丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级血量上限丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['血量上限仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['血量上限神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级速度丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级速度丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级速度丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['速度仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['速度神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级物攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级物攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级物攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物攻资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物攻资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级法攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级法攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级法攻资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法攻资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法攻资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级物防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级物防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级物防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物防资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['物防资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级法防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级法防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级法防资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法防资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['法防资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级血量上限资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级血量上限资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级血量上限资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['血量上限资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['血量上限资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['初级速度资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['中级速度资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['高级速度资质丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['速度资质仙丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['速度资质神丹'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="1"},
	['必杀秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['连击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['吸血秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['蛮力秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['突击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['反弹秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['复仇秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['飞行秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['坚韧秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['法伤秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['闪避秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['凝神秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['冥思秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['再生秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['金睛秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['迅捷秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['神佑秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['命中秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级必杀秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级连击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级吸血秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级蛮力秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级突击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级反弹秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级复仇秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级飞行秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级坚韧秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级法伤秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级闪避秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级凝神秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级冥思秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级再生秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级金睛秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级迅捷秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级神佑秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['高级命中秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级必杀秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级连击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级吸血秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级蛮力秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级突击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级反弹秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级复仇秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级飞行秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级坚韧秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级法伤秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级闪避秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级凝神秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级冥思秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级再生秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级金睛秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级迅捷秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级神佑秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['超级命中秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['迟钝秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['追击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['隐身秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['鬼魂秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['魅惑秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['震慑秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['破防秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['断筋秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['剧毒秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['舍身一击秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['剑气四射秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['焚烧秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['毁魄秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['碎灵秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['驱鬼秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['烈焰风暴秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['雷动九天秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['冰封万里秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['连击术秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['善恶有报秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['善恶有报大秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['善恶有报小秘籍'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能6加1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能8加1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能10加2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能13加2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能16加2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能18加2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能16加3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能20加3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能24加3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能28加3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},
	['宠物技能32加3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="2"},	
	['技能提取卡1'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="4"},
	['技能提取卡2'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="4"},
	['技能提取卡3'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="4"},
	['技能绑定符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="5"},
	['技能解绑符'] = {GuideType=7, GuideCoef1="PetUI", GuideCoef2="2", GuideCoef3="5"},
  }
  
  QuikOpenConfig.TypeConf2={
    ["1-7-1"]={GuideType=9, GuideCoef1="PetUI", GuideCoef2="1", GuideCoef3="3"},
    ["1-7-2"]={GuideType=9, GuideCoef1="PetUI", GuideCoef2="1", GuideCoef3="3"},
    ["1-7-3"]={GuideType=9, GuideCoef1="PetUI", GuideCoef2="1", GuideCoef3="3"},
    ["1-7-4"]={GuideType=9, GuideCoef1="PetUI", GuideCoef2="1", GuideCoef3="3"},
	}